version: "3.3"
services:
  redis:
    image: redis
    container_name: cashbag_redis
    ports:
      - 6379:6379
    networks:
      - cashbag
  mongo:
    image: mongo:latest
    container_name: cashbag_mongo
    ports:
      - "27017:27017"
    volumes:
      - data_mongo:/data/db
    networks:
      - cashbag

volumes:
  data_mongo:

networks:
  cashbag:
